### ISSUE TITLE
manager should be able to skip even if he is the only manager. if he skips there is no review and it should be skipped in final score as well

### ISSUE THREAD

**Issue by manishiitg** [pythexcel/tms_python#210]

**Comment by pythexcel** [comment]
There is some changes in skip_review api. added a admin setting.
->There also need to add setting key on the frontend for control skip review settings 
->for now, I have added default settings in config.py file settings will not get in db then it will take from config file.
->default_skip_settings = {
    "skip_review":True,
    "only_manager_skip":True
}
