### ISSUE TITLE
there should be an option to reset ratings. right now, rating keep going even if job profile happens on increment happens 

### ISSUE THREAD

**Issue by manishiitg** [pythexcel/tms_python#211]

**Comment by manishiitg** [comment]
when we change persons KRA/KPI. there should be a popup which shows up and ask if we need to reset all previous calcuation.

this will mainly reset personals rating to 0 and start from fresh. this will not delete persons preivious data. only the reating time should change

**Comment by pythexcel** [comment]
Api endpoint = system/rating_reset/<string:user_id>
methods=["PUT"]
Required parameters = "user_id"
Header = Admin Token 
Body = None
