### ISSUE TITLE
having montly weekly review is very taxing. need to review altnates to make this easier and fluid 

### ISSUE THREAD

**Issue by manishiitg** [pythexcel/tms_python#212]

**Comment by manishiitg** [comment]
this should be a settings in the admin. which can be turned on/off

if this is off
a) montly reports will go away from left menu
b) no notifcation
c) scores will not show for montly reating 
d) anything else if missed it.


this should be for weekly also. i.e admin can turn weeky off and put on montly. that should also be possible

**Comment by pythexcel** [comment]
Api endpoint = /system/put/reports_settings
method = Put
payload = {
	"weekly_status":true,
	"monthly_status":false
}
header = admin token

Api for get settings
Api endpoint = /system/get/reports_settings
Method = get
header = auth token only
